// ======= DO NOT EDIT THIS FILE ============
class Balloon {
  String owner;
  int color,size;
  Balloon() {
   }
  Balloon(String xOwner, int xColor, int xSize){
    owner=xOwner;color=xColor; size=xSize;
   }
  public String toString(){
    return("(" +owner+","+color + "," + size + ")");
   }
 }
